import {cases} from '../tests/cases.mjs';
import {writeFileSync} from 'node:fs';
const literal=s=>JSON.stringify(s);
const source='// Generated by scripts/generate-tests.mjs from tests/cases.mjs.\n\n'+cases.map(c=>`///|\ntest ${literal(c.name)} {\n  let r = @guard.compare_text(${literal(c.oldText)}, ${literal(c.newText)})\n  assert_eq(r.status, ${literal(c.status)})\n  ${c.rule?`assert_true(r.findings.any(f => f.rule == ${literal(c.rule)}))`:'assert_true(r.errors.is_empty() == (r.status != "invalid"))'}\n}\n`).join('\n');
writeFileSync(new URL('../guard_test.mbt',import.meta.url),source);
console.log(`Generated ${cases.length} MoonBit behavioral tests`);
